import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { NavbarDemo } from "@/components/navbar/navbar";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({
	variable: "--font-inter-sans",
	subsets: ["latin"],
});
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.variable}  antialiased `}>
				<ThemeProvider>
					<NavbarDemo />
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
